const words1 = [
    {
      word: 'address',
      translation: 'adres',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'age',
      translation: 'wiek',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'date od birth',
      translation: 'data urodzenia',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'divorced',
      translation: 'rozwiedziony',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'female',
      translation: 'kobieta',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'first name',
      translation: 'imię',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'gender',
      translation: 'płeć',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'male',
      translation: 'mężczyzna',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'marital status',
      translation: 'stan cywilny',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'married',
      translation: 'żonaty',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'nationality',
      translation: 'narodowość',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'occupation',
      translation: 'zawód',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'single',
      translation: 'stanu wolnego',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'surname',
      translation: 'nazwisko',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'widowed',
      translation: 'owdowiały',
      level: 'basic',
      type: 'personal data',
      image: '',
    },
    {
      word: 'country od residence',
      translation: 'kraj zamieszkania',
      level: 'advanced',
      type: 'personal data',
      image: '',
    },
    {
      word: 'distinguishing features',
      translation: 'znaki szczególne',
      level: 'advanced',
      type: 'personal data',
      image: '',
    },
    {
      word: 'ethnic origin',
      translation: 'pochodzenie etniczne',
      level: 'advanced',
      type: 'personal data',
      image: '',
    },
    {
      word: 'next of kin',
      translation: 'najbliższy krewny',
      level: 'advanced',
      type: 'personal data',
      image: '',
    },
];
