const words2 = [
    {
      word: 'attractive',
      translation: 'atrakcyjny', 
      level: 'basic',
      type: 'apperance',
      image: '',
    },
    {
      word: 'unattractive',
      translation: 'nieatrakcyjny', 
      level: 'basic',
      type: 'apperance',
      image: '',
    },
    {
      word: 'beautiful',
      translation: 'piękny', 
      level: 'basic',
      type: 'apperance',
      image: '',
    },
    {
      word: 'fit',
      translation: 'sprawny',
      translation2: 'w dobrej formie', 
      level: 'basic',
      type: 'apperance',
      image: '',
    },
    {
      word: 'good-looking',
      translation: 'przystojny',
      translation2: 'ładny',
      level: 'basic',
      type: 'apperance',
      image: '',
    },
    {
      word: 'handsome',
      translation: 'przystojny',
      level: 'basic',
      type: 'apperance',
      image: '',
    },
    {
      word: 'plain',
      translation: 'pospoliny',
      translation2: 'nieatrakcyjny',
      level: 'basic',
      type: 'apperance',
      image: '',
    },
    {
      word: 'pretty',
      translation: 'ładny',
      level: 'basic',
      type: 'apperance',
      image: '',
    },
    {
      word: 'ugly',
      translation: 'brzydki',
      level: 'basic',
      type: 'apperance',
      image: '',
    },
    // // // // //
    {
      word: 'cut down on',
      translation: 'ograniczać (ilość czegoś)',
      level: 'basic',
      type: 'apperance expressions',
      image: '',
    },
    {
      word: 'go for (darker colours)',
      translation: 'wybierać',
      translation: 'sięgać po (ciemniejsze kolory)',
      level: 'basic',
      type: 'apperance expressions',
      image: '',
    },
    {
      word: 'paint your nails',
      translation: 'malować paznokcie',
      level: 'basic',
      type: 'apperance expressions',
      image: '',
    },
    {
      word: 'put on weight',
      translation: 'przybierać na wadze',
      level: 'basic',
      type: 'apperance expressions',
      image: '',
    },
    {
      word: 'lose weight',
      translation: 'tracić na wadze',
      level: 'basic',
      type: 'apperance expressions',
      image: '',
    },
    {
      word: 'straighten',
      translation: 'prostować (włosy)',
      level: 'basic',
      type: 'apperance expressions',
      image: '',
    },
    {
      word: 'take up a hobby',
      translation: 'zacząć uprawiać hobby',
      level: 'basic',
      type: 'apperance expressions',
      image: '',
    },
    {
      word: 'take up a sport)',
      translation: 'zacząć uprawiać sport)',
      level: 'basic',
      type: 'apperance expressions',
      image: '',
    },
    // // // // //
    {
      word: 'fat',
      translation: 'gruby',
      level: 'basic',
      type: 'build',
      image: '',
    },
    {
      word: 'muscular',
      translation: 'umięśniony',
      level: 'basic',
      type: 'build',
      image: '',
    },
    {
      word: 'obese',
      translation: 'otyły',
      level: 'basic',
      type: 'build',
      image: '',
    },
    {
      word: 'overweight',
      translation: 'z nadwagą',
      level: 'basic',
      type: 'build',
      image: '',
    },
    {
      word: 'underweight',
      translation: 'z niedowagą',
      level: 'basic',
      type: 'build',
      image: '',
    },
    {
      word: 'słplump',
      translation: 'puszysty',
      translation2: 'pulchny',
      level: 'basic',
      type: 'build',
      image: '',
    },
    {
      word: 'skinny',
      translation: 'chudy',
      level: 'basic',
      type: 'build',
      image: '',
    },
    {
      word: 'slim',
      translation: 'szczupły',
      level: 'basic',
      type: 'build',
      image: '',
    },
    {
      word: 'well-built',
      translation: 'dobrze zbudowany',
      level: 'basic',
      type: 'build',
      image: '',
    },
    // // //
    {
      word: 'lanky',
      translation: 'tyczkowaty',
      translation2: 'wysoki i chudy',
      level: 'extended',
      type: 'build',
      image: '',
    },
    {
      word: 'stocky',
      translation: 'krępy',
      level: 'extended',
      type: 'build',
      image: '',
    },
    // // // // //
    {
      word: 'bald',
      translation: 'łysy',
      level: 'basic',
      type: 'hair',
      image: '',
    },
    {
      word: 'blond',
      translation: 'blond',
      level: 'basic',
      type: 'hair',
      image: '',
    },
    {
      word: 'curly',
      translation: 'kręcone',
      level: 'basic',
      type: 'hair',
      image: '',
    },
    {
      word: 'dark',
      translation: 'ciemne',
      level: 'basic',
      type: 'hair',
      image: '',
    },
    {
      word: 'dyed',
      translation: 'farbowane',
      level: 'basic',
      type: 'hair',
      image: '',
    },
    {
      word: 'red',
      translation: 'rude',
      level: 'basic',
      type: 'hair',
      image: '',
    },
    {
      word: 'shoulder-length',
      translation: 'do ramion',
      level: 'basic',
      type: 'hair',
      image: '',
    },
    {
      word: 'straight',
      translation: 'proste',
      level: 'basic',
      type: 'hair',
      image: '',
    },
    {
      word: 'wavy',
      translation: 'falujące',
      level: 'basic',
      type: 'hair',
      image: '',
    },
    // // //
    {
      word: 'auburn',
      translation: 'kasztanowe',
      level: 'extended',
      type: 'hair',
      image: '',
    },
    {
      word: 'fine',
      translation: 'cienkie',
      translation2: 'rzadkie',
      level: 'extended',
      type: 'hair',
      image: '',
    },
    {
      word: 'thick',
      translation: 'gęste',
      level: 'extended',
      type: 'hair',
      image: '',
    },
    {
      word: 'fringe',
      translation: 'grzywka',
      level: 'extended',
      type: 'hair',
      image: '',
    },
    {
      word: 'have a centre parting',
      translation: 'mieć przedziałek na środku',
      level: 'extended',
      type: 'hair',
      image: '',
    },
    {
      word: 'have a side parting',
      translation: 'mieć przedziałek z boku',
      level: 'extended',
      type: 'hair',
      image: '',
    },
    {
      word: 'ponytail',
      translation: 'kitka',
      translation2: 'koński ogon',
      level: 'extended',
      type: 'hair',
      image: '',
    },
    {
      word: 'receding hairline',
      translation: 'włosy rzednące na skroniach',
      level: 'extended',
      type: 'hair',
      image: '',
    },
    {
      word: 'wear your hair loose',
      translation: 'nosić rozpuszczone włosy',
      level: 'extended',
      type: 'hair',
      image: '',
    },
    {
      word: 'wear your hair up',
      translation: 'nosić spięte włosy',
      level: 'extended',
      type: 'hair',
      image: '',
    },
    // // // // //
    {
      word: 'słówko',
      translation: 'tłumaczenie',
      level: 'basic',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'beard',
      translation: 'broda',
      level: 'basic',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'freckles',
      translation: 'piegi',
      level: 'basic',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'moustache',
      translation: 'wąsy',
      level: 'basic',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'pale complexion',
      translation: 'blada cera',
      level: 'basic',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'tanned complexion',
      translation: 'opalona cera',
      level: 'basic',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'dark complexion',
      translation: 'ciemna cera',
      level: 'basic',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'pierced ears',
      translation: 'przekute uszy',
      level: 'basic',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'scar',
      translation: 'blizna',
      level: 'basic',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'spotty',
      translation: 'pryszczaty',
      level: 'basic',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'tattoo',
      translation: 'tatuaż',
      level: 'basic',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'wrinkles',
      translation: 'zmarszczki',
      level: 'basic',
      type: 'distingushing features',
      image: '',
    },
    // // //
    {
      word: 'birthmark',
      translation: 'znamię',
      level: 'extended',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'clean-shaven',
      translation: 'gładko ogolony',
      level: 'extended',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'clear skin',
      translation: 'gładka skóra',
      level: 'extended',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'double chin',
      translation: 'podwójny podbródek',
      level: 'extended',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'high cheekbones',
      translation: 'wystające kości policzkowe',
      level: 'extended',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'high forehead',
      translation: 'wysokie czoło',
      level: 'extended',
      type: 'distingushing features',
      image: '',
    },
    {
      word: 'piercing blue eyes',
      translation: 'przenikliwe niebieskie oczy',
      level: 'extended',
      type: 'distingushing features',
      image: '',
    },
];
