const words3 = [
    {
      word: 'blouse',
      translation: 'bluzka', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'boots',
      translation: 'wysokie buty', 
      translation2: 'kozaki', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'bra',
      translation: 'biustonosz', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'casual',
      translation: 'codzienny', 
      translation: 'swobodny', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'coat',
      translation: 'płaszcz', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'dress',
      translation: 'sukienka', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'fashionable',
      word2: 'trendy',
      translation: 'modny', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'fleece',
      translation: 'bluza polarowa', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'gloves',
      translation: 'rękawiczki', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'hat',
      translation: 'kapelusz', 
      translation: 'czapka', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'jacket',
      translation: 'kurtka', 
      translation2: 'marynarka', 
      translation3: 'żakiet', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'jumper',
      translation: 'sweter', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'old-fashioned',
      translation: 'staromodny', 
      translation2: 'staroświecki', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'pyjamas',
      translation: 'piżama', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'sandals',
      translation: 'sandały', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'shirt',
      translation: 'koszula', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'shoes',
      translation: 'buty', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'shorts',
      translation: 'szorty', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'skirt',
      translation: 'spódnica', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'smart',
      translation: 'elegancki', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'socks',
      translation: 'skarpety', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'suit',
      translation: 'garnitur', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'sweatshirt',
      translation: 'bluza sportowa', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'tracksuit',
      translation: 'dres', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'trainers',
      translation: 'obuwie sportowe', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'throusers',
      translation: 'spodnie', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'underwear',
      translation: 'bielizna', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'waistcoat',
      translation: 'kamizelka', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    {
      word: 'wear',
      translation: 'nosić', 
      translation2: 'mieć na sobie', 
      level: 'basic',
      type: 'clothes',
      image: '',
    },
    // // //
    {
      word: 'ballgown',
      translation: 'suknia balowa', 
      level: 'extended',
      type: 'clothes',
      image: '',
    },
    {
      word: 'boat-necked',
      translation: 'z szerokim dekoltem (bluzka, sweter)', 
      level: 'extended',
      type: 'clothes',
      image: '',
    },
    {
      word: 'cardigan',
      translation: 'rozpinany sweter', 
      level: 'extended',
      type: 'clothes',
      image: '',
    },
    {
      word: 'colaar',
      translation: 'kołnieżyk', 
      level: 'extended',
      type: 'clothes',
      image: '',
    },
    {
      word: 'cuffs',
      translation: 'mankiety', 
      level: 'extended',
      type: 'clothes',
      image: '',
    },
    {
      word: 'dressing gown',
      translation: 'szlafrok', 
      level: 'extended',
      type: 'clothes',
      image: '',
    },
    {
      word: 'hight heels',
      translation: 'wysokie obcasy', 
      level: 'extended',
      type: 'clothes',
      image: '',
    },
    {
      word: 'hoodie',
      translation: 'bluza z kapturem', 
      level: 'extended',
      type: 'clothes',
      image: '',
    },
    {
      word: 'long-sleeved',
      translation: 'z długim rękawem (koszula)', 
      level: 'extended',
      type: 'clothes',
      image: '',
    },
    {
      word: 'short-sleeved',
      translation: 'z krótkim rękawem (koszula)', 
      level: 'extended',
      type: 'clothes',
      image: '',
    },
    {
      word: 'strapless top',
      translation: 'bluzka bez ramiączek', 
      level: 'extended',
      type: 'clothes',
      image: '',
    },
    {
      word: 'V-neck',
      translation: 'dekolt w szpic', 
      level: 'extended',
      type: 'clothes',
      image: '',
    },
    // // // // //
    {
      word: 'belt',
      translation: 'pasek', 
      level: 'basic',
      type: 'accessories',
      image: '',
    },
    {
      word: 'button',
      translation: 'guzik', 
      level: 'basic',
      type: 'accessories',
      image: '',
    },
    {
      word: 'cap',
      translation: 'czapka z daszkiem', 
      level: 'basic',
      type: 'accessories',
      image: '',
    },
    {
      word: 'earrings',
      translation: 'kolczyki', 
      level: 'basic',
      type: 'accessories',
      image: '',
    },
    {
      word: 'glasses',
      translation: 'okulary', 
      level: 'basic',
      type: 'accessories',
      image: '',
    },
    {
      word: 'handbag',
      word2: 'bag',
      translation: 'torebka', 
      level: 'basic',
      type: 'accessories',
      image: '',
    },
    {
      word: 'jewellery',
      translation: 'biżuteria', 
      level: 'basic',
      type: 'accessories',
      image: '',
    },
    {
      word: 'necklace',
      translation: 'naszyjnik', 
      level: 'basic',
      type: 'accessories',
      image: '',
    },
    {
      word: 'ring',
      translation: 'pierścionek', 
      level: 'basic',
      type: 'accessories',
      image: '',
    },
    {
      word: 'scarf',
      translation: 'szalik', 
      level: 'basic',
      type: 'accessories',
      image: '',
    },
    {
      word: 'tie',
      translation: 'krawat', 
      level: 'basic',
      type: 'accessories',
      image: '',
    },
    // // //
    {
      word: 'bracelet',
      translation: 'bransoletka', 
      level: 'extended',
      type: 'accessories',
      image: '',
    },
    {
      word: 'brooch',
      translation: 'broszka', 
      level: 'extended',
      type: 'accessories',
      image: '',
    },
    {
      word: 'shoe laces',
      translation: 'sznurówki', 
      level: 'extended',
      type: 'accessories',
      image: '',
    },
    {
      word: 'slippers',
      translation: 'kapcie', 
      level: 'extended',
      type: 'accessories',
      image: '',
    },
    {
      word: 'zip-up',
      translation: 'na zamek', 
      level: 'extended',
      type: 'accessories',
      image: '',
    },
    // // // // //
    {
      word: 'checked',
      translation: 'w kratę', 
      level: 'basic',
      type: 'patterns and materials',
      image: '',
    },
    {
      word: 'cotton',
      translation: 'bawełna', 
      level: 'basic',
      type: 'patterns and materials',
      image: '',
    },
    {
      word: 'gold',
      translation: 'złoto', 
      level: 'basic',
      type: 'patterns and materials',
      image: '',
    },
    {
      word: 'leather',
      translation: 'skóra', 
      translation2: 'skórzany', 
      level: 'basic',
      type: 'patterns and materials',
      image: '',
    },
    {
      word: 'plain',
      translation: 'gładki', 
      level: 'basic',
      type: 'patterns and materials',
      image: '',
    },
    {
      word: 'silk',
      translation: 'jedwab', 
      level: 'basic',
      type: 'patterns and materials',
      image: '',
    },
    {
      word: 'silver',
      translation: 'srebro', 
      translation2: 'srebrny', 
      level: 'basic',
      type: 'patterns and materials',
      image: '',
    },
    {
      word: 'spotted',
      translation: 'w kropki', 
      level: 'basic',
      type: 'patterns and materials',
      image: '',
    },
    {
      word: 'striped',
      translation: 'w paski', 
      level: 'basic',
      type: 'patterns and materials',
      image: '',
    },
    {
      word: 'tartan',
      translation: 'w szkodzką kratę', 
      level: 'basic',
      type: 'patterns and materials',
      image: '',
    },
    {
      word: 'wool',
      translation: 'wełna', 
      level: 'basic',
      type: 'patterns and materials',
      image: '',
    },
    // // // // //
    {
      word: 'elactic',
      translation: 'elastyczny', 
      level: 'extended',
      type: 'patterns and materials',
      image: '',
    },
    {
      word: 'fur',
      translation: 'futro', 
      translation2: 'futrzany', 
      level: 'extended',
      type: 'patterns and materials',
      image: '',
    },
    {
      word: 'lacy',
      translation: 'koronkowy', 
      level: 'extended',
      type: 'patterns and materials',
      image: '',
    },
    {
      word: 'lined',
      translation: 'na podszewce', 
      translation2: 'ocieplany', 
      level: 'extended',
      type: 'patterns and materials',
      image: '',
    },
];