const words4 = [
  {
    word: 'aggressive',
    translation: 'agresywny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'ambitious',
    translation: 'ambitny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'bad-tempered',
    translation: 'wybuchowy', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'big-headed',
    translation: 'zarozumiały', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'brave',
    translation: 'odważny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'careful',
    translation: 'ostrożny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'careless',
    translation: 'nieostrożny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'caring',
    translation: 'troskliwy', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'cheerful',
    translation: 'radosny', 
    translation2: 'pogodny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'clever',
    translation: 'mądry', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'confident',
    translation: 'pewny siebie', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'overconfident',
    translation: 'zbyt pewny siebie', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'drama queen',
    translation: 'panikarz', 
    translation2: 'osoba nadmiernie dramatyzująca', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'easygoing',
    translation: 'wyluzowany', 
    translation2: 'opanowany', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'energetic',
    translation: 'energiczny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'extrovert',
    translation: 'ekstrawertyk', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'friendly',
    translation: 'przyjacielski', 
    translation2: 'miły', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'fun-loving',
    translation: 'lubiacy dobrą zabawę', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'generous',
    translation: 'szczodry', 
    translation2: 'hojny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'gentle',
    translation: 'delikatny', 
    translation2: 'łagodny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'hard-working',
    translation: 'pracowity', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'helpful',
    translation: 'uczynny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'unhelpful',
    translation: 'nieskory do pomocy', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'honest',
    translation: 'uczciwy', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'dishonest',
    translation: 'nieuczciwy', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'imaginative',
    translation: 'pomysłowy', 
    translation2: 'kreatywny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'unimaginative',
    translation: 'bez wyobraźni', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'independent',
    translation: 'niezależny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'intelligent',
    translation: 'inteligentny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'introvert',
    translation: 'introwertyk', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'lazy',
    translation: 'leniwy', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'mean',
    translation: 'skąpy', 
    translation2: 'złośliwy', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'messy',
    translation: 'bałaganiarski', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'nasty',
    translation: 'złośliwy', 
    translation2: 'wstrętny', 
    translation3: 'nieprzyjemny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'nice',
    translation: 'miły', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'open',
    translation: 'otwarty', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'optimistic',
    translation: 'optymistyczny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'pessimistic',
    translation: 'pesymistyczny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'outgoing',
    translation: 'otwarty', 
    translation: 'towarzyski', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'patient',
    translation: 'cierpliwy', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'impatient',
    translation: 'niecierpliwy', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'polite',
    translation: 'uprzejmy', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'quiet',
    translation: 'cichy', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'reliable',
    translation: 'solidny', 
    translation2: 'niezawodny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'unreliable',
    translation: 'niesolidny', 
    translation2: 'zawodny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },

  {
    word: 'responsible',
    translation: 'odpowiedzialny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'rude',
    translation: 'niegrzeczny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'selfish',
    translation: 'samolubny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'unselfish',
    translation: 'bezinteresowny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'serious',
    translation: 'poważny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'shy',
    translation: 'nieśmiały', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'silly',
    translation: 'niemądry',
    translation2: 'głupkowaty',
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'sociable',
    translation: 'towarzyski', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'unsociable',
    translation: 'nietowarzyski', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'talkative',
    translation: 'gadatliwy', 
    translation2: 'rozmowny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'tidy',
    translation: 'schludny', 
    translation2: 'porządny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'untidy',
    translation: 'niechlujny', 
    level: 'basic',
    type: 'features of characters',
    image: '',
  },
  // // //
  {
    word: 'bossy',
    translation: 'apodyktyczny', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'cowardly',
    translation: 'tchórzliwy', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'eccentric',
    translation: 'ekscentryczny', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'materialistic',
    translation: 'materialistyczny', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'modest',
    translation: 'skromny', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'moody',
    translation: 'kapryśny', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'odd',
    translation: 'dziwny', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'oddball',
    translation: 'dziwak', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'sensitive',
    translation: 'wrażliwy', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'sincere',
    translation: 'szczery', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'sympathetic',
    translation: 'życzliwy', 
    translation2: 'współczujący', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'weird',
    translation: 'dziwny', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'weirdo',
    translation: 'dziwak',
    translation2: 'dziwaczka',
    translation3: 'dziwadło', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'whizzkid',
    translation: 'cudowne dziecko', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  {
    word: 'withdrawn',
    translation: 'zamknięty w sobie', 
    level: 'extended',
    type: 'features of characters',
    image: '',
  },
  
];