const words5 = [
  {
    word: 'angry',
    translation: 'zły',
    translation2: 'rozgniewany',
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'annoyed',
    translation: 'zirytowany', 
    translation2: 'rozdrażniony', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'be in a good mood',
    translation: 'być w dobrym humorze', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'be in a bad mood',
    translation: 'być w złym humorze', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'bored',
    translation: 'znudzony', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'cross',
    translation: 'zły', 
    translation2: 'rozgniewany', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'depressed',
    translation: 'załamany', 
    translation2: 'przygnębiony', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'didappointed',
    translation: 'zawstydzony', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'excited',
    translation: 'podekscytowany', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'exhausted',
    translation: 'wyczerpany', 
    translation2: 'zmęczony', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'frightened',
    translation: 'przerażony', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'nervous',
    translation: 'zdenerwowany', 
    translation2: 'spięty', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'pleased',
    translation: 'zadowolony', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'relaxed',
    translation: 'zrelaksowany', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'scared',
    translation: 'wystraszony', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'shocked',
    translation: 'zszokowany', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'stressed',
    translation: 'zestresowany', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'surprised',
    translation: 'zdziwiony', 
    translation2: 'zaskoczony', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'tired',
    translation: 'zmęczony', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'upset',
    translation: 'przygnębiony', 
    translation2: 'zaniepokojony', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'worried',
    translation: 'zmartwiony', 
    level: 'basic',
    type: 'feelings and emotions',
    image: '',
  },
  // // //
  {
    word: 'amazed',
    translation: 'zdumiony', 
    translation2: 'zdziwiony', 
    level: 'extended',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'delighted',
    translation: 'zachwycony', 
    level: 'extended',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'nagging feeling',
    translation: 'dręczące uczucie', 
    level: 'extended',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'petrified',
    translation: 'przerażony', 
    level: 'extended',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'shattered',
    translation: 'zdruzgotany', 
    translation2: 'wykończony', 
    level: 'extended',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'stunned',
    translation: 'oniemiały', 
    translation2: 'osłupiały', 
    level: 'extended',
    type: 'feelings and emotions',
    image: '',
  },
  {
    word: 'worn out',
    translation: 'wycieńczony', 
    translation2: 'wyczerpany', 
    level: 'extended',
    type: 'feelings and emotions',
    image: '',
  },
];