const words7 = [
	{
		word: 'abortion',
		translation: 'aborcja', 
		level: 'basic',
		type: 'ethnical problems',
		image: '',
	},
	{
		word: 'charity',
		translation: 'dobroczynność', 
		translation2: 'ogranizacja charytatywna', 
		level: 'basic',
		type: 'ethnical problems',
		image: '',
	},
	{
		word: 'drug abuse',
		translation: 'zażywanie narkotyków', 
		level: 'basic',
		type: 'ethnical problems',
		image: '',
	},
	{
		word: 'fair trade',
		translation: 'sprawiedliwy handel', 
		level: 'basic',
		type: 'ethnical problems',
		image: '',
	},
	{
		word: 'homelessness',
		translation: 'bezdomność', 
		level: 'basic',
		type: 'ethnical problems',
		image: '',
	},
	{
		word: 'unemployment',
		translation: 'bezrobocie', 
		level: 'basic',
		type: 'ethnical problems',
		image: '',
	},
	{
		word: 'corruption',
		translation: 'korupcja', 
		level: 'basic',
		type: 'ethnical problems',
		image: '',
	},
	{
		word: 'racism',
		translation: 'rasizm', 
		level: 'basic',
		type: 'ethnical problems',
		image: '',
	},
	// // //
	{
		word: 'dealth penatly',
		translation: 'kara śmierci', 
		level: 'extended',
		type: 'ethnical problems',
		image: '',
	},
	{
		word: 'eutanasia',
		translation: 'eutanazja', 
		level: 'extended',
		type: 'ethnical problems',
		image: '',
	},
	{
		word: 'freedom of speech',
		translation: 'wolność słowa', 
		level: 'extended',
		type: 'ethnical problems',
		image: '',
	},
	{
		word: 'gambling',
		translation: 'hazard', 
		level: 'extended',
		type: 'ethnical problems',
		image: '',
	},
	{
		word: 'genetic engineering',
		translation: 'inżynieria genetyczna', 
		level: 'extended',
		type: 'ethnical problems',
		image: '',
	},
	{
		word: 'privacy',
		translation: 'prywatność', 
		level: 'extended',
		type: 'ethnical problems',
		image: '',
	},
];